[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/altschool-exam"
  to = "http://54.221.12.246"
  status = 200
  force = true


[build]
  command = "npm run build"
publish= "build/"
